---
kind: pipeline
type: docker
name: default

steps:
  - name: lint
    image: nicklehmann/poetry:py3.8-latest-alpine
    commands:
      - rm poetry.lock
      - poetry install
      - poetry run flake8
  - name: publish
    image: nicklehmann/poetry:py3.8-latest-alpine
    commands:
      - poetry install
      - poetry publish --build --username $USERNAME --password $PASSWORD
    environment:
      USERNAME:
        from_secret: pypi_username
      PASSWORD:
        from_secret: pypi_password
    when:
      event:
        - push
      branch:
        - master
    failure: ignore
